{{- if .Values.istio.enabled }}
---
# la modifica maggiore che abbiamo è quella di avere due route nel virtual service di istio
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  gateways:
  - {{ template "fullname" . }}
  hosts:
  - {{ template "fullname" . }}.local
  - {{ .Values.ingress.host }}
  http:
  - name: primary
    # le due route al momento son impostate per avere il 100% del traffico sul servizio stable e 0 su quello canary
    route:
    - destination:
        host: {{ template "fullname" . }}
        port:
          number: 80
      weight: 100
    - destination:
        host: {{ template "fullname" . }}-canary
        port:
          number: 80
      weight: 0

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "fullname" . }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
     - "*"
{{- end }}

