{{- if .Values.rollout.enabled }}
---
# son simili a dei Deployment, tutto quello che possiamo definire come Deployment si può definire come Rollout
# le maggiori differenze sono la definizione di due tipologie nuove di deployment:
# spec.strategy: bluegreen | canary
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        istio-injection: enabled
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 12 }}
  strategy:
    # questa è una delle maggiori differenze
    canary:
      # questo è il servizio che verrà deployato come canary
      canaryService: {{ template "fullname" . }}-canary
      # questo è il servizio attualmente presente o comunque quello dove andrà la maggior parte del traffico
      stableService: {{ template "fullname" . }}
      # qua inoltre vediamo come effettuiamo il routing del traffico, nel nostro caso, avendo installato istio, avviene tramite istio
      trafficRouting:
        istio:
          virtualService:
            name: {{ template "fullname" . }}
            routes:
            - primary
      # qua abbiamo gli steps
      steps:
{{ toYaml .Values.rollout.steps | indent 6 }}
{{- if .Values.rollout.analysis.enabled }}
      # qua abbiamo la parte di analysis (skippabile nel nostro caso tramite un valore sullo yaml values)
      analysis:
        templates:
        - templateName: {{ template "fullname" . }}
        startingStep: 2
        args:
        - name: service-name
          value: "{{ template "fullname" . }}-canary.{{ .Release.Namespace }}.svc.cluster.local"
{{- end }}

{{- if .Values.rollout.analysis.enabled }}
---

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ template "fullname" . }}
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] >= 0.8
    failureCondition: result[0] < 0.8
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.monitoring
        query: |
          sum(irate(
            istio_requests_total{  
              reporter="source",
              destination_service=~"{{ "{{args.service-name}}" }}",
              response_code=~"2.*"
            }[2m]
          )) / sum(irate(
            istio_requests_total{
              reporter="source",
              destination_service=~"{{ "{{args.service-name}}" }}"
            }[2m]
          ))
  - name: avg-req-duration
    interval: 10s
    successCondition: result[0] <= 1000
    failureCondition: result[0] > 1000
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.monitoring
        query: |
          sum(irate(
            istio_request_duration_milliseconds_sum{
              reporter="source",
              destination_service=~"{{ "{{args.service-name}}" }}"
            }[2m]
          )) / sum(irate(
            istio_request_duration_milliseconds_count{
              reporter="source",
              destination_service=~"{{ "{{args.service-name}}" }}"
            }[2m]
          ))
{{- end }}
      
---

# questo service verrà usato solo nel processo di release del servizio, negli altri casi, il servizio definito sarà
# quello utilizzato, l'unica cosa che dovrebbe cambiare è il nome
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-canary
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
{{- end }}
